import type { TemplateAsset, Layer } from '@/types'

export const DEFAULT_TEMPLATES: TemplateAsset[] = [
  {
    id: 'tpl-classic-noir',
    name: 'Classic Noir',
    type: 'style',
    summary: 'High contrast classic ASCII with Floyd-Steinberg dithering',
    preset: {
      artStyle: 'classic',
      characterSet: 'detailed',
      ditherAlgorithm: 'floyd-steinberg',
      ditherStrength: 0.9,
      brightness: -0.1,
      contrast: 1.8,
      colorMode: 'grayscale',
      fxPreset: 'noise',
      fxStrength: 0.2,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-matrix-terminal',
    name: 'Matrix Terminal',
    type: 'style',
    summary: 'Green matrix rain with terminal charset',
    preset: {
      artStyle: 'terminal',
      terminalCharset: '101010',
      colorMode: 'matrix',
      fxPreset: 'matrix-rain',
      fxStrength: 0.7,
      matrixScale: 12,
      matrixSpeed: 0.15,
      matrixDirection: 'down',
      brightness: 0.1,
      contrast: 1.4,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-retro-amber',
    name: 'Retro Amber',
    type: 'style',
    summary: 'Warm amber CRT monitor aesthetic',
    preset: {
      artStyle: 'retro',
      retroDuotone: 'amber-classic',
      retroNoise: 0.6,
      colorMode: 'amber',
      fxPreset: 'crt',
      fxStrength: 0.5,
      crtDirection: 'down',
      brightness: 0.05,
      contrast: 1.3,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-braille-dense',
    name: 'Braille Dense',
    type: 'style',
    summary: 'Dense braille pattern with Atkinson dithering',
    preset: {
      artStyle: 'braille',
      brailleVariant: 'dense',
      ditherAlgorithm: 'atkinson',
      ditherStrength: 0.7,
      fontSize: 8,
      characterSpacing: 0.8,
      colorMode: 'grayscale',
      fxPreset: 'none',
    } as Partial<Layer>,
  },
  {
    id: 'tpl-halftone-pop',
    name: 'Halftone Pop',
    type: 'style',
    summary: 'Bold halftone circles with full color',
    preset: {
      artStyle: 'halftone',
      halftoneShape: 'circle',
      halftoneSize: 2.5,
      halftoneRotation: 15,
      colorMode: 'fullcolor',
      ditherAlgorithm: 'bayer',
      ditherStrength: 0.5,
      contrast: 1.5,
      fxPreset: 'none',
    } as Partial<Layer>,
  },
  {
    id: 'tpl-line-sketch',
    name: 'Line Sketch',
    type: 'style',
    summary: 'Sketch-like line art rendering',
    preset: {
      artStyle: 'line',
      lineLength: 2,
      lineWidth: 1.5,
      lineThickness: 1.2,
      lineRotation: 45,
      colorMode: 'grayscale',
      ditherAlgorithm: 'none',
      contrast: 1.6,
      fxPreset: 'noise',
      fxStrength: 0.15,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-particle-storm',
    name: 'Particle Storm',
    type: 'style',
    summary: 'Dense particle field with glitch effects',
    preset: {
      artStyle: 'particles',
      particleDensity: 0.8,
      particleChar: '·',
      colorMode: 'fullcolor',
      fxPreset: 'glitch',
      fxStrength: 0.6,
      glitchDirection: 'right',
      contrast: 1.2,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-cyber-violet',
    name: 'Cyber Violet',
    type: 'style',
    summary: 'Purple haze with beam sweep effect',
    preset: {
      artStyle: 'retro',
      retroDuotone: 'violet-haze',
      retroNoise: 0.3,
      colorMode: 'custom',
      customColor: '#9933ff',
      fxPreset: 'beam',
      fxStrength: 0.4,
      beamDirection: 'right',
      brightness: 0.05,
      contrast: 1.4,
    } as Partial<Layer>,
  },
  {
    id: 'tpl-claude-mode',
    name: 'Claude Mode',
    type: 'style',
    summary: 'Claude-code inspired ASCII rendering',
    preset: {
      artStyle: 'claude-code',
      claudeDensity: 0.6,
      colorMode: 'custom',
      customColor: '#da7756',
      fxPreset: 'intervals',
      fxStrength: 0.3,
      intervalDirection: 'down',
      intervalSpacing: 16,
      intervalSpeed: 0.8,
    } as Partial<Layer>,
  },
]
